### ISSUE TITLE
merge_comp_freqs.py does not handle differences between file separators in file names

### ISSUE THREAD

**Issue by tallguy-hackett** [adamtornhill/maat-scripts#1]
The output from running cloc on Windows uses back slashes `\` instead of forward slashes `/` as file separators.  The output from maat and git (inside Git Bash at least) uses forward slashes `/`.  This causes the comparison of file names to fail for every file comparison except files that do not contain any file separators in the name.  For example in _Your Code as a Crime Scene_ the only output that the script provides for the example is

```
module,revisions,code
project.clj,19,17
```

**Comment by adamtornhill** [comment]
Yes, that's correct. It's a difference I missed to mention in the book. Fortunately, there's a simple workaround: just append the "-unix" argument when running cloc. See here for more info: https://forums.pragprog.com/forums/367/topics/13384

I hope to get around to provide a workaround in the Python script as well.

**Comment by adamtornhill** [comment]
I pushed a workaround for this, but for future editions of the book I'll include a note to Windows users to specify the --unix flag when running cloc.
